### ISSUE TITLE
Having issues with update bio 

### ISSUE THREAD

**Issue by auditism** [IAmJaysWay/web3auth_database#1]
When I click update bio nothing happens, I tried to log the `profileId` and the `bio` in the api/updateBio file and it returns undefined. I also logged the req.body as you can see below..
```
import connectDB from "../../lib/connectDB"
import Users from "../../lib/models/userSchema"

export default async function updateBio(req, res) {
    const { profileId, bio } = req.body

    console.log(req.body)

    console.log(profileId, bio)
    await connectDB()

    try {
        
        await Users.findOneAndUpdate({ profileId: profileId }, { bio: bio })
        res.status(200).json({ bio })
    } catch (error) {
        res.status(400).json({ error })
        console.error(error)
    }
}

```
here is the console response 
![Untitled](https://user-images.githubusercontent.com/99469000/200024030-96ff0d7f-14ce-49d9-83a3-9a09839fda6e.png)
I thought it's because the req.body seems to be a string and we are trying to destructure it. any idea on how to fix this ?

**Comment by GiorgioDalla** [comment]
P.S love your content and energy

**Comment by auditism** [comment]
json.parse the req.body
